spring:
   datasource:
      username: gameup
      password: gameup
      url: jdbc:mysql://localhost:3306/gameup
   jpa:
      defer-datasource-initialization: true
      hibernate:
         ddl-auto: create
      show-sql: true

   sql:
      init:
         mode: always
         